### ISSUE TITLE
Re-enable DiscoveryDNS

### ISSUE THREAD

**Issue by adriancole** [Netflix/denominator#288]
It isn't acceptable for us to release a provider that lacks live tests. At a minimum, DiscoveryDNS needs to implement and have someone run live tests (similar to designate and the others).

Also, the mock tests aren't invoking the custom SSL logic. This means we are further flying blind. MockDiscoveryDNSServer needs to use ssl to ensure the plumbing works.

**Comment by adriancole** [comment]
@wnagele I can help with the mock part and questions on the live tests. We shouldn't release DiscoveryDNS until live tests are in and you or someone else runs them successfully.

**Comment by wnagele** [comment]
I'll look into this. Currently swamped with other work - can't commit to a date just yet.

**Comment by adriancole** [comment]
Ping me privately with credentials if you'd like a hand on the live testing!

**Comment by wnagele** [comment]
@MisterK will be working on this. I just can't find the time at the moment.

**Comment by adriancole** [comment]
cool. @MisterK welcome!

**Comment by adriancole** [comment]
fyi https://github.com/Netflix/denominator/pull/298 adds live tests. they still need to be run, though

**Comment by MisterK** [comment]
@adriancole Hi!
Just wanted to know if you already had a timeline in mind. I would rather work on this at the end of the month, if possible. Would this be fine by you?

**Comment by adriancole** [comment]
Once https://github.com/Netflix/denominator/pull/309 is in, this issue is limited to getting live tests plumbed and passing.

Waiting is fine, but I might unhook discoverydns from the 4.4 release in that case. We shouldn't hold the release hostage as everything else will be ready in 2 weeks. We could always re-add it back in 4.5.

**Comment by adriancole** [comment]
FYI, if anyone can give me discoverydns account credentials, I can at least try to get this into the 4.4 release. else, it will have to bump as I can only do the release this weekend.

**Comment by adriancole** [comment]
bumping to 4.5 via #317

**Comment by adriancole** [comment]
Hi, folks. I'd love to see this addressed, but please note that if I don't have credentials by the time we release 4.5, I will be deleting this provider completely. There's too much unnecessary burden here, and nagging displaced my time that I can use to help the project.

https://groups.google.com/forum/#!topic/denominator-dev/s5jefvKRJNA

**Comment by MisterK** [comment]
@adriancole For the credentials, @wnagele will provide them for you shortly, to test on our test environment.

Thanks!

**Comment by adriancole** [comment]
I can't wait!

**Comment by MisterK** [comment]
I have been able to successfully run most of the Live Tests myself today. I fixed a few problems along the way. I'll send a pull request ASAP (hopefully tomorrow).

**Comment by adriancole** [comment]
Note: re-enabling this is dependent on a process by which contributors can easily test.

Right now, testing requires contributors have a static IP, which is a tall order, and not accessible.

I've asked discoveryDNS to make easy testing a priority. We need this to be accessible via a dynamic IP before adding. Ex. via a bastion, a test endpoint, or a UI that allows self-service whitelisting.

If we can't get a process that makes contributors' life easy, we'll have to ask discoverydns to host their own provider.

**Comment by MisterK** [comment]
@adriancole I had a chat with @wnagele and he explained to me that we might want to externalize the discoveryDNS provider instead, into its own project, to use it as an external "plugin" (that way we can manage the testing and the credentials ourselves).
So I gave it a try.

For the Java code usage, it works very well, I just added the denominator-core and the new separate denominator-discoverydns provider as dependencies to a test client project, and I was then able to use the provider as expected.

However, for the CLI, I wasn't able to use the separate provider. I tried to modify the "denominator-cli-4.4.2-fat.jar" script to use the folder containing the denominator-discoverydns.jar file, but it still only lists the providers included in the fat jar itself. I'm guessing the "executable fat-jar hack" might be the cause of this, but I'm not sure.
Could you please advise if you have a workaround, or if you could add a more flexible way to add custom providers at CLI run-time?
Thanks in advance.

**Comment by adriancole** [comment]
Glad to hear things are working out.

So, the easiest way to make the cli work with a third-party provider is to
either set the classpath to the following.

* Meta-inf/services directory with your provider listed
* Exisiting cli jar
* Your jar

Or make a build file that repackages the cli. It would probably be pretty
simple, two deps: your jar and the existing fat jar. If you use maven, the
"really-executable-jar" plugin should do the trick. Otherwise it would
involve a little gradle work which I could help with in your repo

Lemme know how you would like to proceed.

**Comment by adriancole** [comment]
Actually, just placing the provider jar first in the classpath should work
(as it contains the meta-inf)

**Comment by MisterK** [comment]
I finally made it working.
The problem is that the "really-executable-jar" script uses the "-jar" option, so it ignores the "-cp" option, and you have to use the "Class-Path" manifest entry instead.
So I added it temporarily in the cli project's manifest, and it worked.
The problem is that this manifest entry does not support wildcards, so you cannot add random plugins jars at run-time.

So it leaves me with two options:
* either re-package the fat jar as you mentioned, but that's not really what I wanted, as I think it would be preferable to let end-users just use the standard Denominator jar, just adding Discovery on top, as an optional provider.
* The other possibility would be to ask you to modify the _denominator.Providers_ class, so that is provides its own ClassLoader when calling _ServiceLoader.load(Provider.class)_, so that it could also point to a predefined "plugins" or "providers" directory, where the optional provider jars could just be dropped in.

What do you think?

Other than that, I'll now make a pull request to remove everything DiscoveryDNS-related from the denominator project. And then I'll create our own _denominator-discoverydns_ Github project.

**Comment by adriancole** [comment]
Let's keep this limited to the bash header in the cli. At most extreme, we could introduce an ENV variable which controls where third party providers can be found.

Ex. here's how to make it look for the providers directory.

```
-    shortcutFile << 'exec java -jar $0 "$@"' + "\n"
+    shortcutFile << 'exec java -cp providers/*:$0 denominator.cli.Denominator "$@"' + "\n"
```
I tested this out by unhooking discoverydns, and adding it to the providers directory.

Can you find a solution that is limited to this? I would prefer that, as it seems least change necessary.

**Comment by MisterK** [comment]
OK I quickly tested your solution and it works for me.
Are you going to push that change to the cli? An hard-coded "providers" directory or an ENV variable is fine by me, as I would think that the description on how to extend Denominator through third party providers should probably end up in the Denominator Wiki, so that end-users know how to handle those third party providers. What do you think?

Another quick question: our new project needs to access some of your test infrastructure classes (TestGraph, Live, etc.), from both the denominator-core and the denominator-model projects, as I wouldn't like to duplicate this useful test setup. Would you be keen on making those classes an accessible Gradle dependency?

**Comment by adriancole** [comment]
All sounds good. Yeah sounds like we would publish test jars. Shouldn't be
too hard. I will open an issue around third party provider development to
track this stuff. Thanks for collaborating on this!

-A

**Comment by MisterK** [comment]
I've created the [denominator-discoverydns](https://github.com/discoverydns/denominator-discoverydns) external project.
I'll fix all the remaining problems in the next few days.

Thanks for your help!
